name: Build android apks

on:
  push:
    branches: [main]

jobs:
  build_apk:
    name: Build apk for ${{ matrix.environment }} environment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_mode: [debug, release]
        environment: [DEV, PROD]
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          channel: stable
          flutter-version: 3.16.9
      - name: Install dependencies
        run: flutter pub get
      - name: Build apk
        run: flutter build apk --dart-define=ENVIRONMENT=${{ matrix.environment }} --${{ matrix.build_mode }}
      - name: Upload apk and keep for 15 Days
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Upload ${{ matrix.build_mode }} apk
          path: build/app/outputs/flutter-apk/${{ matrix.build_mode }}/app-${{ matrix.build_mode }}.apk
          retention-days: 15
